services:
  catalogdb:
    image: postgres:17
  basketdb:
    image: postgres:17
  distributedCache:
    image: redis
  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

volumes:
  postgres_catalog: 
  postgres_basket:
